/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authorizedLayoutRouteImport } from './routes/(authorized)/layout'
import { Route as unauthorizedLayoutRouteImport } from './routes/(unauthorized)/layout'
import { Route as authorizedorganizationLayoutRouteImport } from './routes/(authorized)/(organization)/layout'
import { Route as authorizedorganizationsidebarLayoutRouteImport } from './routes/(authorized)/(organization)/(sidebar)/layout'
import { Route as authorizedCreateOrganizationPageRouteImport } from './routes/(authorized)/create-organization/page'
import { Route as authorizedJoinOrganizationPageRouteImport } from './routes/(authorized)/join-organization/page'
import { Route as authorizedSelectOrganizationPageRouteImport } from './routes/(authorized)/select-organization/page'
import { Route as unauthorizedResetPasswordPageRouteImport } from './routes/(unauthorized)/reset-password/page'
import { Route as unauthorizedSetNewPasswordPageRouteImport } from './routes/(unauthorized)/set-new-password/page'
import { Route as unauthorizedSigninPageRouteImport } from './routes/(unauthorized)/signin/page'
import { Route as unauthorizedSignupPageRouteImport } from './routes/(unauthorized)/signup/page'
import { Route as authorizedorganizationsidebarPageRouteImport } from './routes/(authorized)/(organization)/(sidebar)/page'
import { Route as authorizedorganizationsidebarSettingsLayoutRouteImport } from './routes/(authorized)/(organization)/(sidebar)/settings/layout'
import { Route as authorizedorganizationInviteMembersPageRouteImport } from './routes/(authorized)/(organization)/invite-members/page'
import { Route as authorizedorganizationsidebarSplatPageRouteImport } from './routes/(authorized)/(organization)/(sidebar)/$/page'
import { Route as authorizedorganizationsidebarCreateImagePageRouteImport } from './routes/(authorized)/(organization)/(sidebar)/create-image/page'
import { Route as authorizedorganizationsidebarCreateVideoPageRouteImport } from './routes/(authorized)/(organization)/(sidebar)/create-video/page'
import { Route as authorizedorganizationsidebarEditImagePageRouteImport } from './routes/(authorized)/(organization)/(sidebar)/edit-image/page'
import { Route as authorizedorganizationsidebarEnhancePageRouteImport } from './routes/(authorized)/(organization)/(sidebar)/enhance/page'
import { Route as authorizedorganizationsidebarSettingsPageRouteImport } from './routes/(authorized)/(organization)/(sidebar)/settings/page'
import { Route as authorizedorganizationsidebarCreateImageSessionIdPageRouteImport } from './routes/(authorized)/(organization)/(sidebar)/create-image/$sessionId/page'
import { Route as authorizedorganizationsidebarCreateVideoSessionIdPageRouteImport } from './routes/(authorized)/(organization)/(sidebar)/create-video/$sessionId/page'
import { Route as authorizedorganizationsidebarEditImageSessionIdPageRouteImport } from './routes/(authorized)/(organization)/(sidebar)/edit-image/$sessionId/page'
import { Route as authorizedorganizationsidebarEnhanceSessionIdPageRouteImport } from './routes/(authorized)/(organization)/(sidebar)/enhance/$sessionId/page'
import { Route as authorizedorganizationsidebarSettingsAccountPageRouteImport } from './routes/(authorized)/(organization)/(sidebar)/settings/account/page'
import { Route as authorizedorganizationsidebarSettingsMembersPageRouteImport } from './routes/(authorized)/(organization)/(sidebar)/settings/members/page'
import { Route as authorizedorganizationsidebarSettingsOrganizationPageRouteImport } from './routes/(authorized)/(organization)/(sidebar)/settings/organization/page'
import { Route as authorizedorganizationsidebarSettingsRolesPageRouteImport } from './routes/(authorized)/(organization)/(sidebar)/settings/roles/page'

const authorizedLayoutRoute = authorizedLayoutRouteImport.update({
  id: '/(authorized)',
  getParentRoute: () => rootRouteImport,
} as any)
const unauthorizedLayoutRoute = unauthorizedLayoutRouteImport.update({
  id: '/(unauthorized)',
  getParentRoute: () => rootRouteImport,
} as any)
const authorizedorganizationLayoutRoute =
  authorizedorganizationLayoutRouteImport.update({
    id: '/(organization)',
    getParentRoute: () => authorizedLayoutRoute,
  } as any)
const authorizedorganizationsidebarLayoutRoute =
  authorizedorganizationsidebarLayoutRouteImport.update({
    id: '/(sidebar)',
    getParentRoute: () => authorizedorganizationLayoutRoute,
  } as any)
const authorizedCreateOrganizationPageRoute =
  authorizedCreateOrganizationPageRouteImport.update({
    id: '/create-organization/',
    path: '/create-organization/',
    getParentRoute: () => authorizedLayoutRoute,
  } as any)
const authorizedJoinOrganizationPageRoute =
  authorizedJoinOrganizationPageRouteImport.update({
    id: '/join-organization/',
    path: '/join-organization/',
    getParentRoute: () => authorizedLayoutRoute,
  } as any)
const authorizedSelectOrganizationPageRoute =
  authorizedSelectOrganizationPageRouteImport.update({
    id: '/select-organization/',
    path: '/select-organization/',
    getParentRoute: () => authorizedLayoutRoute,
  } as any)
const unauthorizedResetPasswordPageRoute =
  unauthorizedResetPasswordPageRouteImport.update({
    id: '/reset-password/',
    path: '/reset-password/',
    getParentRoute: () => unauthorizedLayoutRoute,
  } as any)
const unauthorizedSetNewPasswordPageRoute =
  unauthorizedSetNewPasswordPageRouteImport.update({
    id: '/set-new-password/',
    path: '/set-new-password/',
    getParentRoute: () => unauthorizedLayoutRoute,
  } as any)
const unauthorizedSigninPageRoute = unauthorizedSigninPageRouteImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => unauthorizedLayoutRoute,
} as any)
const unauthorizedSignupPageRoute = unauthorizedSignupPageRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => unauthorizedLayoutRoute,
} as any)
const authorizedorganizationsidebarPageRoute =
  authorizedorganizationsidebarPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authorizedorganizationsidebarLayoutRoute,
  } as any)
const authorizedorganizationsidebarSettingsLayoutRoute =
  authorizedorganizationsidebarSettingsLayoutRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => authorizedorganizationsidebarLayoutRoute,
  } as any)
const authorizedorganizationInviteMembersPageRoute =
  authorizedorganizationInviteMembersPageRouteImport.update({
    id: '/invite-members/',
    path: '/invite-members/',
    getParentRoute: () => authorizedorganizationLayoutRoute,
  } as any)
const authorizedorganizationsidebarSplatPageRoute =
  authorizedorganizationsidebarSplatPageRouteImport.update({
    id: '/$/',
    path: '/$/',
    getParentRoute: () => authorizedorganizationsidebarLayoutRoute,
  } as any)
const authorizedorganizationsidebarCreateImagePageRoute =
  authorizedorganizationsidebarCreateImagePageRouteImport.update({
    id: '/create-image/',
    path: '/create-image/',
    getParentRoute: () => authorizedorganizationsidebarLayoutRoute,
  } as any)
const authorizedorganizationsidebarCreateVideoPageRoute =
  authorizedorganizationsidebarCreateVideoPageRouteImport.update({
    id: '/create-video/',
    path: '/create-video/',
    getParentRoute: () => authorizedorganizationsidebarLayoutRoute,
  } as any)
const authorizedorganizationsidebarEditImagePageRoute =
  authorizedorganizationsidebarEditImagePageRouteImport.update({
    id: '/edit-image/',
    path: '/edit-image/',
    getParentRoute: () => authorizedorganizationsidebarLayoutRoute,
  } as any)
const authorizedorganizationsidebarEnhancePageRoute =
  authorizedorganizationsidebarEnhancePageRouteImport.update({
    id: '/enhance/',
    path: '/enhance/',
    getParentRoute: () => authorizedorganizationsidebarLayoutRoute,
  } as any)
const authorizedorganizationsidebarSettingsPageRoute =
  authorizedorganizationsidebarSettingsPageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authorizedorganizationsidebarSettingsLayoutRoute,
  } as any)
const authorizedorganizationsidebarCreateImageSessionIdPageRoute =
  authorizedorganizationsidebarCreateImageSessionIdPageRouteImport.update({
    id: '/create-image/$sessionId/',
    path: '/create-image/$sessionId/',
    getParentRoute: () => authorizedorganizationsidebarLayoutRoute,
  } as any)
const authorizedorganizationsidebarCreateVideoSessionIdPageRoute =
  authorizedorganizationsidebarCreateVideoSessionIdPageRouteImport.update({
    id: '/create-video/$sessionId/',
    path: '/create-video/$sessionId/',
    getParentRoute: () => authorizedorganizationsidebarLayoutRoute,
  } as any)
const authorizedorganizationsidebarEditImageSessionIdPageRoute =
  authorizedorganizationsidebarEditImageSessionIdPageRouteImport.update({
    id: '/edit-image/$sessionId/',
    path: '/edit-image/$sessionId/',
    getParentRoute: () => authorizedorganizationsidebarLayoutRoute,
  } as any)
const authorizedorganizationsidebarEnhanceSessionIdPageRoute =
  authorizedorganizationsidebarEnhanceSessionIdPageRouteImport.update({
    id: '/enhance/$sessionId/',
    path: '/enhance/$sessionId/',
    getParentRoute: () => authorizedorganizationsidebarLayoutRoute,
  } as any)
const authorizedorganizationsidebarSettingsAccountPageRoute =
  authorizedorganizationsidebarSettingsAccountPageRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => authorizedorganizationsidebarSettingsLayoutRoute,
  } as any)
const authorizedorganizationsidebarSettingsMembersPageRoute =
  authorizedorganizationsidebarSettingsMembersPageRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => authorizedorganizationsidebarSettingsLayoutRoute,
  } as any)
const authorizedorganizationsidebarSettingsOrganizationPageRoute =
  authorizedorganizationsidebarSettingsOrganizationPageRouteImport.update({
    id: '/organization/',
    path: '/organization/',
    getParentRoute: () => authorizedorganizationsidebarSettingsLayoutRoute,
  } as any)
const authorizedorganizationsidebarSettingsRolesPageRoute =
  authorizedorganizationsidebarSettingsRolesPageRouteImport.update({
    id: '/roles/',
    path: '/roles/',
    getParentRoute: () => authorizedorganizationsidebarSettingsLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/create-organization/': typeof authorizedCreateOrganizationPageRoute
  '/join-organization/': typeof authorizedJoinOrganizationPageRoute
  '/select-organization/': typeof authorizedSelectOrganizationPageRoute
  '/reset-password/': typeof unauthorizedResetPasswordPageRoute
  '/set-new-password/': typeof unauthorizedSetNewPasswordPageRoute
  '/signin/': typeof unauthorizedSigninPageRoute
  '/signup/': typeof unauthorizedSignupPageRoute
  '/settings': typeof authorizedorganizationsidebarSettingsLayoutRouteWithChildren
  '/': typeof authorizedorganizationsidebarPageRoute
  '/invite-members/': typeof authorizedorganizationInviteMembersPageRoute
  '/$/': typeof authorizedorganizationsidebarSplatPageRoute
  '/create-image/': typeof authorizedorganizationsidebarCreateImagePageRoute
  '/create-video/': typeof authorizedorganizationsidebarCreateVideoPageRoute
  '/edit-image/': typeof authorizedorganizationsidebarEditImagePageRoute
  '/enhance/': typeof authorizedorganizationsidebarEnhancePageRoute
  '/settings/': typeof authorizedorganizationsidebarSettingsPageRoute
  '/create-image/$sessionId/': typeof authorizedorganizationsidebarCreateImageSessionIdPageRoute
  '/create-video/$sessionId/': typeof authorizedorganizationsidebarCreateVideoSessionIdPageRoute
  '/edit-image/$sessionId/': typeof authorizedorganizationsidebarEditImageSessionIdPageRoute
  '/enhance/$sessionId/': typeof authorizedorganizationsidebarEnhanceSessionIdPageRoute
  '/settings/account/': typeof authorizedorganizationsidebarSettingsAccountPageRoute
  '/settings/members/': typeof authorizedorganizationsidebarSettingsMembersPageRoute
  '/settings/organization/': typeof authorizedorganizationsidebarSettingsOrganizationPageRoute
  '/settings/roles/': typeof authorizedorganizationsidebarSettingsRolesPageRoute
}
export interface FileRoutesByTo {
  '/create-organization': typeof authorizedCreateOrganizationPageRoute
  '/join-organization': typeof authorizedJoinOrganizationPageRoute
  '/select-organization': typeof authorizedSelectOrganizationPageRoute
  '/reset-password': typeof unauthorizedResetPasswordPageRoute
  '/set-new-password': typeof unauthorizedSetNewPasswordPageRoute
  '/signin': typeof unauthorizedSigninPageRoute
  '/signup': typeof unauthorizedSignupPageRoute
  '/': typeof authorizedorganizationsidebarPageRoute
  '/invite-members': typeof authorizedorganizationInviteMembersPageRoute
  '/$': typeof authorizedorganizationsidebarSplatPageRoute
  '/create-image': typeof authorizedorganizationsidebarCreateImagePageRoute
  '/create-video': typeof authorizedorganizationsidebarCreateVideoPageRoute
  '/edit-image': typeof authorizedorganizationsidebarEditImagePageRoute
  '/enhance': typeof authorizedorganizationsidebarEnhancePageRoute
  '/settings': typeof authorizedorganizationsidebarSettingsPageRoute
  '/create-image/$sessionId': typeof authorizedorganizationsidebarCreateImageSessionIdPageRoute
  '/create-video/$sessionId': typeof authorizedorganizationsidebarCreateVideoSessionIdPageRoute
  '/edit-image/$sessionId': typeof authorizedorganizationsidebarEditImageSessionIdPageRoute
  '/enhance/$sessionId': typeof authorizedorganizationsidebarEnhanceSessionIdPageRoute
  '/settings/account': typeof authorizedorganizationsidebarSettingsAccountPageRoute
  '/settings/members': typeof authorizedorganizationsidebarSettingsMembersPageRoute
  '/settings/organization': typeof authorizedorganizationsidebarSettingsOrganizationPageRoute
  '/settings/roles': typeof authorizedorganizationsidebarSettingsRolesPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authorized)': typeof authorizedLayoutRouteWithChildren
  '/(unauthorized)': typeof unauthorizedLayoutRouteWithChildren
  '/(authorized)/(organization)': typeof authorizedorganizationLayoutRouteWithChildren
  '/(authorized)/(organization)/(sidebar)': typeof authorizedorganizationsidebarLayoutRouteWithChildren
  '/(authorized)/create-organization/': typeof authorizedCreateOrganizationPageRoute
  '/(authorized)/join-organization/': typeof authorizedJoinOrganizationPageRoute
  '/(authorized)/select-organization/': typeof authorizedSelectOrganizationPageRoute
  '/(unauthorized)/reset-password/': typeof unauthorizedResetPasswordPageRoute
  '/(unauthorized)/set-new-password/': typeof unauthorizedSetNewPasswordPageRoute
  '/(unauthorized)/signin/': typeof unauthorizedSigninPageRoute
  '/(unauthorized)/signup/': typeof unauthorizedSignupPageRoute
  '/(authorized)/(organization)/(sidebar)/settings': typeof authorizedorganizationsidebarSettingsLayoutRouteWithChildren
  '/(authorized)/(organization)/(sidebar)/': typeof authorizedorganizationsidebarPageRoute
  '/(authorized)/(organization)/invite-members/': typeof authorizedorganizationInviteMembersPageRoute
  '/(authorized)/(organization)/(sidebar)/$/': typeof authorizedorganizationsidebarSplatPageRoute
  '/(authorized)/(organization)/(sidebar)/create-image/': typeof authorizedorganizationsidebarCreateImagePageRoute
  '/(authorized)/(organization)/(sidebar)/create-video/': typeof authorizedorganizationsidebarCreateVideoPageRoute
  '/(authorized)/(organization)/(sidebar)/edit-image/': typeof authorizedorganizationsidebarEditImagePageRoute
  '/(authorized)/(organization)/(sidebar)/enhance/': typeof authorizedorganizationsidebarEnhancePageRoute
  '/(authorized)/(organization)/(sidebar)/settings/': typeof authorizedorganizationsidebarSettingsPageRoute
  '/(authorized)/(organization)/(sidebar)/create-image/$sessionId/': typeof authorizedorganizationsidebarCreateImageSessionIdPageRoute
  '/(authorized)/(organization)/(sidebar)/create-video/$sessionId/': typeof authorizedorganizationsidebarCreateVideoSessionIdPageRoute
  '/(authorized)/(organization)/(sidebar)/edit-image/$sessionId/': typeof authorizedorganizationsidebarEditImageSessionIdPageRoute
  '/(authorized)/(organization)/(sidebar)/enhance/$sessionId/': typeof authorizedorganizationsidebarEnhanceSessionIdPageRoute
  '/(authorized)/(organization)/(sidebar)/settings/account/': typeof authorizedorganizationsidebarSettingsAccountPageRoute
  '/(authorized)/(organization)/(sidebar)/settings/members/': typeof authorizedorganizationsidebarSettingsMembersPageRoute
  '/(authorized)/(organization)/(sidebar)/settings/organization/': typeof authorizedorganizationsidebarSettingsOrganizationPageRoute
  '/(authorized)/(organization)/(sidebar)/settings/roles/': typeof authorizedorganizationsidebarSettingsRolesPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/create-organization/'
    | '/join-organization/'
    | '/select-organization/'
    | '/reset-password/'
    | '/set-new-password/'
    | '/signin/'
    | '/signup/'
    | '/settings'
    | '/'
    | '/invite-members/'
    | '/$/'
    | '/create-image/'
    | '/create-video/'
    | '/edit-image/'
    | '/enhance/'
    | '/settings/'
    | '/create-image/$sessionId/'
    | '/create-video/$sessionId/'
    | '/edit-image/$sessionId/'
    | '/enhance/$sessionId/'
    | '/settings/account/'
    | '/settings/members/'
    | '/settings/organization/'
    | '/settings/roles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/create-organization'
    | '/join-organization'
    | '/select-organization'
    | '/reset-password'
    | '/set-new-password'
    | '/signin'
    | '/signup'
    | '/'
    | '/invite-members'
    | '/$'
    | '/create-image'
    | '/create-video'
    | '/edit-image'
    | '/enhance'
    | '/settings'
    | '/create-image/$sessionId'
    | '/create-video/$sessionId'
    | '/edit-image/$sessionId'
    | '/enhance/$sessionId'
    | '/settings/account'
    | '/settings/members'
    | '/settings/organization'
    | '/settings/roles'
  id:
    | '__root__'
    | '/(authorized)'
    | '/(unauthorized)'
    | '/(authorized)/(organization)'
    | '/(authorized)/(organization)/(sidebar)'
    | '/(authorized)/create-organization/'
    | '/(authorized)/join-organization/'
    | '/(authorized)/select-organization/'
    | '/(unauthorized)/reset-password/'
    | '/(unauthorized)/set-new-password/'
    | '/(unauthorized)/signin/'
    | '/(unauthorized)/signup/'
    | '/(authorized)/(organization)/(sidebar)/settings'
    | '/(authorized)/(organization)/(sidebar)/'
    | '/(authorized)/(organization)/invite-members/'
    | '/(authorized)/(organization)/(sidebar)/$/'
    | '/(authorized)/(organization)/(sidebar)/create-image/'
    | '/(authorized)/(organization)/(sidebar)/create-video/'
    | '/(authorized)/(organization)/(sidebar)/edit-image/'
    | '/(authorized)/(organization)/(sidebar)/enhance/'
    | '/(authorized)/(organization)/(sidebar)/settings/'
    | '/(authorized)/(organization)/(sidebar)/create-image/$sessionId/'
    | '/(authorized)/(organization)/(sidebar)/create-video/$sessionId/'
    | '/(authorized)/(organization)/(sidebar)/edit-image/$sessionId/'
    | '/(authorized)/(organization)/(sidebar)/enhance/$sessionId/'
    | '/(authorized)/(organization)/(sidebar)/settings/account/'
    | '/(authorized)/(organization)/(sidebar)/settings/members/'
    | '/(authorized)/(organization)/(sidebar)/settings/organization/'
    | '/(authorized)/(organization)/(sidebar)/settings/roles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authorizedLayoutRoute: typeof authorizedLayoutRouteWithChildren
  unauthorizedLayoutRoute: typeof unauthorizedLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(authorized)': {
      id: '/(authorized)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authorizedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(unauthorized)': {
      id: '/(unauthorized)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof unauthorizedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authorized)/(organization)': {
      id: '/(authorized)/(organization)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authorizedorganizationLayoutRouteImport
      parentRoute: typeof authorizedLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)': {
      id: '/(authorized)/(organization)/(sidebar)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authorizedorganizationsidebarLayoutRouteImport
      parentRoute: typeof authorizedorganizationLayoutRoute
    }
    '/(authorized)/create-organization/': {
      id: '/(authorized)/create-organization/'
      path: '/create-organization'
      fullPath: '/create-organization/'
      preLoaderRoute: typeof authorizedCreateOrganizationPageRouteImport
      parentRoute: typeof authorizedLayoutRoute
    }
    '/(authorized)/join-organization/': {
      id: '/(authorized)/join-organization/'
      path: '/join-organization'
      fullPath: '/join-organization/'
      preLoaderRoute: typeof authorizedJoinOrganizationPageRouteImport
      parentRoute: typeof authorizedLayoutRoute
    }
    '/(authorized)/select-organization/': {
      id: '/(authorized)/select-organization/'
      path: '/select-organization'
      fullPath: '/select-organization/'
      preLoaderRoute: typeof authorizedSelectOrganizationPageRouteImport
      parentRoute: typeof authorizedLayoutRoute
    }
    '/(unauthorized)/reset-password/': {
      id: '/(unauthorized)/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof unauthorizedResetPasswordPageRouteImport
      parentRoute: typeof unauthorizedLayoutRoute
    }
    '/(unauthorized)/set-new-password/': {
      id: '/(unauthorized)/set-new-password/'
      path: '/set-new-password'
      fullPath: '/set-new-password/'
      preLoaderRoute: typeof unauthorizedSetNewPasswordPageRouteImport
      parentRoute: typeof unauthorizedLayoutRoute
    }
    '/(unauthorized)/signin/': {
      id: '/(unauthorized)/signin/'
      path: '/signin'
      fullPath: '/signin/'
      preLoaderRoute: typeof unauthorizedSigninPageRouteImport
      parentRoute: typeof unauthorizedLayoutRoute
    }
    '/(unauthorized)/signup/': {
      id: '/(unauthorized)/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof unauthorizedSignupPageRouteImport
      parentRoute: typeof unauthorizedLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)/': {
      id: '/(authorized)/(organization)/(sidebar)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authorizedorganizationsidebarPageRouteImport
      parentRoute: typeof authorizedorganizationsidebarLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)/settings': {
      id: '/(authorized)/(organization)/(sidebar)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof authorizedorganizationsidebarSettingsLayoutRouteImport
      parentRoute: typeof authorizedorganizationsidebarLayoutRoute
    }
    '/(authorized)/(organization)/invite-members/': {
      id: '/(authorized)/(organization)/invite-members/'
      path: '/invite-members'
      fullPath: '/invite-members/'
      preLoaderRoute: typeof authorizedorganizationInviteMembersPageRouteImport
      parentRoute: typeof authorizedorganizationLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)/$/': {
      id: '/(authorized)/(organization)/(sidebar)/$/'
      path: '/$'
      fullPath: '/$/'
      preLoaderRoute: typeof authorizedorganizationsidebarSplatPageRouteImport
      parentRoute: typeof authorizedorganizationsidebarLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)/create-image/': {
      id: '/(authorized)/(organization)/(sidebar)/create-image/'
      path: '/create-image'
      fullPath: '/create-image/'
      preLoaderRoute: typeof authorizedorganizationsidebarCreateImagePageRouteImport
      parentRoute: typeof authorizedorganizationsidebarLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)/create-video/': {
      id: '/(authorized)/(organization)/(sidebar)/create-video/'
      path: '/create-video'
      fullPath: '/create-video/'
      preLoaderRoute: typeof authorizedorganizationsidebarCreateVideoPageRouteImport
      parentRoute: typeof authorizedorganizationsidebarLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)/edit-image/': {
      id: '/(authorized)/(organization)/(sidebar)/edit-image/'
      path: '/edit-image'
      fullPath: '/edit-image/'
      preLoaderRoute: typeof authorizedorganizationsidebarEditImagePageRouteImport
      parentRoute: typeof authorizedorganizationsidebarLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)/enhance/': {
      id: '/(authorized)/(organization)/(sidebar)/enhance/'
      path: '/enhance'
      fullPath: '/enhance/'
      preLoaderRoute: typeof authorizedorganizationsidebarEnhancePageRouteImport
      parentRoute: typeof authorizedorganizationsidebarLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)/settings/': {
      id: '/(authorized)/(organization)/(sidebar)/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof authorizedorganizationsidebarSettingsPageRouteImport
      parentRoute: typeof authorizedorganizationsidebarSettingsLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)/create-image/$sessionId/': {
      id: '/(authorized)/(organization)/(sidebar)/create-image/$sessionId/'
      path: '/create-image/$sessionId'
      fullPath: '/create-image/$sessionId/'
      preLoaderRoute: typeof authorizedorganizationsidebarCreateImageSessionIdPageRouteImport
      parentRoute: typeof authorizedorganizationsidebarLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)/create-video/$sessionId/': {
      id: '/(authorized)/(organization)/(sidebar)/create-video/$sessionId/'
      path: '/create-video/$sessionId'
      fullPath: '/create-video/$sessionId/'
      preLoaderRoute: typeof authorizedorganizationsidebarCreateVideoSessionIdPageRouteImport
      parentRoute: typeof authorizedorganizationsidebarLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)/edit-image/$sessionId/': {
      id: '/(authorized)/(organization)/(sidebar)/edit-image/$sessionId/'
      path: '/edit-image/$sessionId'
      fullPath: '/edit-image/$sessionId/'
      preLoaderRoute: typeof authorizedorganizationsidebarEditImageSessionIdPageRouteImport
      parentRoute: typeof authorizedorganizationsidebarLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)/enhance/$sessionId/': {
      id: '/(authorized)/(organization)/(sidebar)/enhance/$sessionId/'
      path: '/enhance/$sessionId'
      fullPath: '/enhance/$sessionId/'
      preLoaderRoute: typeof authorizedorganizationsidebarEnhanceSessionIdPageRouteImport
      parentRoute: typeof authorizedorganizationsidebarLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)/settings/account/': {
      id: '/(authorized)/(organization)/(sidebar)/settings/account/'
      path: '/account'
      fullPath: '/settings/account/'
      preLoaderRoute: typeof authorizedorganizationsidebarSettingsAccountPageRouteImport
      parentRoute: typeof authorizedorganizationsidebarSettingsLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)/settings/members/': {
      id: '/(authorized)/(organization)/(sidebar)/settings/members/'
      path: '/members'
      fullPath: '/settings/members/'
      preLoaderRoute: typeof authorizedorganizationsidebarSettingsMembersPageRouteImport
      parentRoute: typeof authorizedorganizationsidebarSettingsLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)/settings/organization/': {
      id: '/(authorized)/(organization)/(sidebar)/settings/organization/'
      path: '/organization'
      fullPath: '/settings/organization/'
      preLoaderRoute: typeof authorizedorganizationsidebarSettingsOrganizationPageRouteImport
      parentRoute: typeof authorizedorganizationsidebarSettingsLayoutRoute
    }
    '/(authorized)/(organization)/(sidebar)/settings/roles/': {
      id: '/(authorized)/(organization)/(sidebar)/settings/roles/'
      path: '/roles'
      fullPath: '/settings/roles/'
      preLoaderRoute: typeof authorizedorganizationsidebarSettingsRolesPageRouteImport
      parentRoute: typeof authorizedorganizationsidebarSettingsLayoutRoute
    }
  }
}

interface authorizedorganizationsidebarSettingsLayoutRouteChildren {
  authorizedorganizationsidebarSettingsPageRoute: typeof authorizedorganizationsidebarSettingsPageRoute
  authorizedorganizationsidebarSettingsAccountPageRoute: typeof authorizedorganizationsidebarSettingsAccountPageRoute
  authorizedorganizationsidebarSettingsMembersPageRoute: typeof authorizedorganizationsidebarSettingsMembersPageRoute
  authorizedorganizationsidebarSettingsOrganizationPageRoute: typeof authorizedorganizationsidebarSettingsOrganizationPageRoute
  authorizedorganizationsidebarSettingsRolesPageRoute: typeof authorizedorganizationsidebarSettingsRolesPageRoute
}

const authorizedorganizationsidebarSettingsLayoutRouteChildren: authorizedorganizationsidebarSettingsLayoutRouteChildren =
  {
    authorizedorganizationsidebarSettingsPageRoute:
      authorizedorganizationsidebarSettingsPageRoute,
    authorizedorganizationsidebarSettingsAccountPageRoute:
      authorizedorganizationsidebarSettingsAccountPageRoute,
    authorizedorganizationsidebarSettingsMembersPageRoute:
      authorizedorganizationsidebarSettingsMembersPageRoute,
    authorizedorganizationsidebarSettingsOrganizationPageRoute:
      authorizedorganizationsidebarSettingsOrganizationPageRoute,
    authorizedorganizationsidebarSettingsRolesPageRoute:
      authorizedorganizationsidebarSettingsRolesPageRoute,
  }

const authorizedorganizationsidebarSettingsLayoutRouteWithChildren =
  authorizedorganizationsidebarSettingsLayoutRoute._addFileChildren(
    authorizedorganizationsidebarSettingsLayoutRouteChildren,
  )

interface authorizedorganizationsidebarLayoutRouteChildren {
  authorizedorganizationsidebarSettingsLayoutRoute: typeof authorizedorganizationsidebarSettingsLayoutRouteWithChildren
  authorizedorganizationsidebarPageRoute: typeof authorizedorganizationsidebarPageRoute
  authorizedorganizationsidebarSplatPageRoute: typeof authorizedorganizationsidebarSplatPageRoute
  authorizedorganizationsidebarCreateImagePageRoute: typeof authorizedorganizationsidebarCreateImagePageRoute
  authorizedorganizationsidebarCreateVideoPageRoute: typeof authorizedorganizationsidebarCreateVideoPageRoute
  authorizedorganizationsidebarEditImagePageRoute: typeof authorizedorganizationsidebarEditImagePageRoute
  authorizedorganizationsidebarEnhancePageRoute: typeof authorizedorganizationsidebarEnhancePageRoute
  authorizedorganizationsidebarCreateImageSessionIdPageRoute: typeof authorizedorganizationsidebarCreateImageSessionIdPageRoute
  authorizedorganizationsidebarCreateVideoSessionIdPageRoute: typeof authorizedorganizationsidebarCreateVideoSessionIdPageRoute
  authorizedorganizationsidebarEditImageSessionIdPageRoute: typeof authorizedorganizationsidebarEditImageSessionIdPageRoute
  authorizedorganizationsidebarEnhanceSessionIdPageRoute: typeof authorizedorganizationsidebarEnhanceSessionIdPageRoute
}

const authorizedorganizationsidebarLayoutRouteChildren: authorizedorganizationsidebarLayoutRouteChildren =
  {
    authorizedorganizationsidebarSettingsLayoutRoute:
      authorizedorganizationsidebarSettingsLayoutRouteWithChildren,
    authorizedorganizationsidebarPageRoute:
      authorizedorganizationsidebarPageRoute,
    authorizedorganizationsidebarSplatPageRoute:
      authorizedorganizationsidebarSplatPageRoute,
    authorizedorganizationsidebarCreateImagePageRoute:
      authorizedorganizationsidebarCreateImagePageRoute,
    authorizedorganizationsidebarCreateVideoPageRoute:
      authorizedorganizationsidebarCreateVideoPageRoute,
    authorizedorganizationsidebarEditImagePageRoute:
      authorizedorganizationsidebarEditImagePageRoute,
    authorizedorganizationsidebarEnhancePageRoute:
      authorizedorganizationsidebarEnhancePageRoute,
    authorizedorganizationsidebarCreateImageSessionIdPageRoute:
      authorizedorganizationsidebarCreateImageSessionIdPageRoute,
    authorizedorganizationsidebarCreateVideoSessionIdPageRoute:
      authorizedorganizationsidebarCreateVideoSessionIdPageRoute,
    authorizedorganizationsidebarEditImageSessionIdPageRoute:
      authorizedorganizationsidebarEditImageSessionIdPageRoute,
    authorizedorganizationsidebarEnhanceSessionIdPageRoute:
      authorizedorganizationsidebarEnhanceSessionIdPageRoute,
  }

const authorizedorganizationsidebarLayoutRouteWithChildren =
  authorizedorganizationsidebarLayoutRoute._addFileChildren(
    authorizedorganizationsidebarLayoutRouteChildren,
  )

interface authorizedorganizationLayoutRouteChildren {
  authorizedorganizationsidebarLayoutRoute: typeof authorizedorganizationsidebarLayoutRouteWithChildren
  authorizedorganizationInviteMembersPageRoute: typeof authorizedorganizationInviteMembersPageRoute
}

const authorizedorganizationLayoutRouteChildren: authorizedorganizationLayoutRouteChildren =
  {
    authorizedorganizationsidebarLayoutRoute:
      authorizedorganizationsidebarLayoutRouteWithChildren,
    authorizedorganizationInviteMembersPageRoute:
      authorizedorganizationInviteMembersPageRoute,
  }

const authorizedorganizationLayoutRouteWithChildren =
  authorizedorganizationLayoutRoute._addFileChildren(
    authorizedorganizationLayoutRouteChildren,
  )

interface authorizedLayoutRouteChildren {
  authorizedorganizationLayoutRoute: typeof authorizedorganizationLayoutRouteWithChildren
  authorizedCreateOrganizationPageRoute: typeof authorizedCreateOrganizationPageRoute
  authorizedJoinOrganizationPageRoute: typeof authorizedJoinOrganizationPageRoute
  authorizedSelectOrganizationPageRoute: typeof authorizedSelectOrganizationPageRoute
}

const authorizedLayoutRouteChildren: authorizedLayoutRouteChildren = {
  authorizedorganizationLayoutRoute:
    authorizedorganizationLayoutRouteWithChildren,
  authorizedCreateOrganizationPageRoute: authorizedCreateOrganizationPageRoute,
  authorizedJoinOrganizationPageRoute: authorizedJoinOrganizationPageRoute,
  authorizedSelectOrganizationPageRoute: authorizedSelectOrganizationPageRoute,
}

const authorizedLayoutRouteWithChildren =
  authorizedLayoutRoute._addFileChildren(authorizedLayoutRouteChildren)

interface unauthorizedLayoutRouteChildren {
  unauthorizedResetPasswordPageRoute: typeof unauthorizedResetPasswordPageRoute
  unauthorizedSetNewPasswordPageRoute: typeof unauthorizedSetNewPasswordPageRoute
  unauthorizedSigninPageRoute: typeof unauthorizedSigninPageRoute
  unauthorizedSignupPageRoute: typeof unauthorizedSignupPageRoute
}

const unauthorizedLayoutRouteChildren: unauthorizedLayoutRouteChildren = {
  unauthorizedResetPasswordPageRoute: unauthorizedResetPasswordPageRoute,
  unauthorizedSetNewPasswordPageRoute: unauthorizedSetNewPasswordPageRoute,
  unauthorizedSigninPageRoute: unauthorizedSigninPageRoute,
  unauthorizedSignupPageRoute: unauthorizedSignupPageRoute,
}

const unauthorizedLayoutRouteWithChildren =
  unauthorizedLayoutRoute._addFileChildren(unauthorizedLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authorizedLayoutRoute: authorizedLayoutRouteWithChildren,
  unauthorizedLayoutRoute: unauthorizedLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
